### ISSUE TITLE
Please publish to maven central

### ISSUE THREAD

**Issue by SteinerOk** [Teamwork/android-multiautocomplete#5]
Currently, android-multiautocomplete releases appear to only be published to jcenter and are not present on maven central. JCenter has a long history of artifact integrity issues and we try to avoid it at all costs. I recognize that maven central's publishing process is sometimes considered more tedious, but this signing/verification process is part of why it's preferred.

https://blog.autsoft.hu/a-confusing-dependency
https://twitter.com/jakewharton/status/1073102730443526144?lang=en

This has taken on some more immediacy due to the imminent shutdown of jcenter: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by marcosalis** [comment]
Hi there, thank you for reporting this.
As you mentioned `jcenter` is due to be shut down soon, so we are looking into alternatives to be able to reliably publish the library in the future. We will keep you posted! 👍

**Comment by marcosalis** [comment]
Hi @SteinerOk , the library is now available on Maven Central from this release:
https://github.com/Teamwork/android-multiautocomplete/releases/tag/v0.4.0

Please check out the instructions (`groupId` has changed).
Thanks for your patience!
